增加group的tailwind
AC11-Take-Off-Team/Lax pull request #12
Opened 2022-08-31 11:31 UTC by KathyLEEKUANYI

增加初步group的tailwind

2022-09-01 12:57 UTC, puyichun approved these changes

2022-09-03 06:23 UTC, cacachang commented on app/javascript/controllers/hello_controller.js
> -//   <h1 data-target="hello.output"></h1>
可以解釋一下為什麼要刪除嗎.........？

2022-09-03 06:23 UTC, cacachang commented on app/views/groups/content.html.erb
> +      描述
這裡記得縮

2022-09-03 06:23 UTC, cacachang commented on app/views/groups/show.html.erb
> +    <div class="text-blue-400 ml-10 mt-8"><%= @group.description %><%= link_to "編輯說明" , edit_group_path(@group) %></div>
排 版

2022-09-03 06:27 UTC, cacachang requested changes
請調整排版 & 禮拜一詢問你刪除部分是什麼

2022-09-03 08:22 UTC, KathyLEEKUANYI commented on app/javascript/controllers/hello_controller.js
> -//   <h1 data-target="hello.output"></h1>
那個是裝stimulus 送的   沒有用就先刪掉了
裡面只有註解

2022-09-05 03:23 UTC, closed without merging