增加頻道創建時間與創建使用者
AC11-Take-Off-Team/Lax pull request #20
Opened 2022-09-01 17:37 UTC by KathyLEEKUANYI

在頻道詳情(content)的地方增加創建時間與創建使用者

2022-09-03 03:34 UTC, puyichun requested changes
group controller content 修改！

2022-09-03 03:34 UTC, puyichun commented on app/controllers/groups_controller.rb
> +    @nickname = current_user.nickname
你這個不是創建者吧！！！！是使用者名稱，你應該是group_params 上面加上:nickname，然後merge(nickname: current_user.nickname)

2022-09-03 03:34 UTC, puyichun commented on app/views/groups/edit.html.erb
> +        <%= form.text_field :description, :class=>"my-2 border-2 rounded text-2xl " %>
text_area

2022-09-03 03:34 UTC, puyichun commented on app/views/groups/index.html.erb
> +      <h4 class="my-2 border-b-2 p-2 "><%= Group.count %>個頻道<h4></h4>
為什麼要有頻道總數量？那樣使用者不就可以知道這個網頁是不是很少人用

2022-09-03 03:34 UTC, puyichun commented on app/views/groups/new.html.erb
> +<script>
用stimulate

2022-09-04 08:21 UTC, cacachang requested changes

2022-09-04 08:21 UTC, cacachang commented on app/views/groups/content.html.erb
> +      <div><%= @nickname %>於<%= @group.created_at.strftime("%Y-%m-%d") %>創建</div>
創建者下面接時間？

2022-09-04 08:21 UTC, cacachang commented on app/views/groups/index.html.erb
> +        <div class="">
這 div 要幹嘛

2022-09-04 08:21 UTC, cacachang commented on app/views/groups/index.html.erb
> +          <button class="mb-2 bg-white hover:bg-gray-100 py-2 px-4 rounded shadow "><%= link_to "退出" , quit_group_path(group),method: "post" %></button>
退出為什麼是用 post

2022-09-04 08:21 UTC, cacachang commented on app/views/groups/index.html.erb
> +      </div>
排版

2022-09-04 08:21 UTC, cacachang commented on app/views/groups/new.html.erb
> +    <p class="my-10 text-gray-500">频道是你的團隊進行通信的地方。圍繞主题進行組織時其效果最佳，例如#市場營銷#。</p>
請問何時才要把簡字改掉

2022-09-04 08:21 UTC, cacachang commented on app/views/groups/new.html.erb
> +        <%= form.text_field :description, :class=>"my-2 border-2 rounded text-2xl" %>
用 text_area 會比較好？

2022-09-04 08:21 UTC, cacachang commented on app/views/groups/new.html.erb
> +      <button>
外面應該不用再包 button ?

2022-09-04 08:21 UTC, cacachang commented on app/views/groups/new.html.erb
> +<script>
是 stimulus 哈哈哈

2022-09-04 08:21 UTC, cacachang commented on app/views/groups/new.html.erb
> +      "設為私人,當频道設置為私人時，只有受邀請之後才能查看或加入。";
頻道

2022-09-04 08:21 UTC, cacachang commented on app/views/groups/show.html.erb
> +<div  class=" h-96 ">
class 空格格式

2022-09-04 09:19 UTC, KathyLEEKUANYI commented on app/views/groups/index.html.erb
> +      <h4 class="my-2 border-b-2 p-2 "><%= Group.count %>個頻道<h4></h4>
這只是給自己看''自己目前有加入多少群組而已''  跟網頁多少人用應該沒有關係 (?

2022-09-04 16:36 UTC, DylanHHY requested changes

2022-09-04 16:36 UTC, DylanHHY commented on app/views/groups/index.html.erb
> +          <button class="mb-2 bg-white hover:bg-gray-100 py-2 px-4 rounded shadow "><%= link_to "退出" , quit_group_path(group),method: "post" %></button>
退出用post有點奇怪

2022-09-04 16:36 UTC, DylanHHY commented on app/views/groups/index.html.erb
> +          <button class="mb-2 bg-blue-500 hover:bg-blue-700 text-white rounded py-2 px-4"><%= link_to "加入" , join_group_path(group),method: "post" %></button>
這邊用button標籤有點奇怪，你自己後面都說是連結了，這樣不是很矛盾嗎？

2022-09-04 16:36 UTC, DylanHHY commented on app/views/groups/new.html.erb
> +    <p class="my-10 text-gray-500">频道是你的團隊進行通信的地方。圍繞主题進行組織時其效果最佳，例如#市場營銷#。</p>
小地方需要注意一下簡字，如果不確定是不是簡字，可以用google翻譯

2022-09-04 16:36 UTC, DylanHHY commented on app/views/groups/new.html.erb
> +      名稱：
你這邊可以用一個標籤包住，之後要調整比較好調。

2022-09-04 16:36 UTC, DylanHHY commented on app/views/groups/new.html.erb
> +      描述:
同上

2022-09-04 16:36 UTC, DylanHHY commented on app/controllers/groups_controller.rb
> +    @nickname = current_user.nickname
用使用者user比較準確

2022-09-05 03:14 UTC, closed without merging