全站首頁
AC11-Take-Off-Team/Lax pull request #22
Opened 2022-09-02 09:54 UTC by KathyLEEKUANYI

全站首頁

2022-09-03 03:36 UTC, puyichun approved these changes

2022-09-03 06:05 UTC, cacachang requested changes

2022-09-03 06:05 UTC, cacachang commented on app/assets/stylesheets/tailwind.css
> +}
咦，為什麼會有這檔案

2022-09-03 06:05 UTC, cacachang commented on app/javascript/stylesheet/index.js
> +import "tailwind.css";
為何這裡要 import tailwind ?

2022-09-03 06:05 UTC, cacachang commented on app/views/home/index.html.erb
> +          >
排版 請不要直接複製貼上沒檢查 謝謝

2022-09-03 06:05 UTC, cacachang commented on app/views/layouts/application.html.erb
> -    <%= render "shared/navbar" %>
為什麼這要刪掉 ～～～～

2022-09-03 06:05 UTC, cacachang commented on app/views/layouts/shared/_search_form.html.erb
> +  <%= f.label ""%>
這蝦米？

2022-09-03 06:05 UTC, cacachang commented on app/views/projects/_projectnav.html.erb
> +        <svg class="fill-current" height="16" focusable="false" viewBox="0 0 32 32"><path d="M23.2,16c0,0.3-0.1,0.7-0.3,0.9l-9,11c-0.5,0.6-1.5,0.7-2.1,0.2s-0.7-1.5-0.2-2.1l8.2-10L11.6,6c-0.5-0.6-0.4-
排版：）））））））））

2022-09-04 09:15 UTC, KathyLEEKUANYI commented on app/javascript/stylesheet/index.js
> +import "tailwind.css";
已刪除

2022-09-04 16:12 UTC, DylanHHY approved these changes

2022-09-04 16:12 UTC, DylanHHY commented on app/views/layouts/shared/_search_form.html.erb
> +  <%= f.label ""%>
這是？？

2022-09-04 16:12 UTC, DylanHHY commented on app/views/layouts/application.html.erb
> -    <%= render "shared/navbar" %>
刪掉以後，你把他放去哪了？

2022-09-04 16:12 UTC, DylanHHY commented on Gemfile
> +
你的套件，可以整理一下嗎？

2022-09-04 16:12 UTC, DylanHHY commented on app/views/home/index.html.erb
> +      Use the messaging tab above for all work-related conversations. For
這邊你是要用英文表示嗎？還是中文？
還有這是你從slack貼過來的？

2022-09-04 16:18 UTC, DylanHHY commented
你都不用解衝突就發PR？

2022-09-04 16:19 UTC, DylanHHY requested changes
解完衝突再發PR

2022-09-05 03:21 UTC, closed without merging