首頁已改縮排
AC11-Take-Off-Team/Lax pull request #30
Opened 2022-09-05 07:39 UTC by KathyLEEKUANYI

2022-09-05 10:09 UTC, DylanHHY approved these changes

2022-09-05 10:42 UTC, cacachang requested changes
縮排還需要調整

2022-09-05 10:42 UTC, cacachang commented on app/views/home/index.html.erb
> +      <div class="flex w-full items-center p-2 transition-all rounded-md text-sm font-semibold text-gray-600 hover:bg-light">
這裡還是沒縮到

2022-09-05 10:42 UTC, cacachang commented on app/views/layouts/shared/_search_form.html.erb
> +  <%= f.label ""%>
為什麼要放空標籤

2022-09-05 10:42 UTC, cacachang commented on app/views/projects/_projectnav.html.erb
> +                        <span class="w-9 h-9 flex items-center justify-center text-icon">
這裡沒縮

2022-09-05 10:42 UTC, cacachang commented on app/views/projects/_projectnav.html.erb
> +                          <span class="w-9 h-9 flex items-center justify-center text-icon">
這個也沒縮

2022-09-05 10:42 UTC, cacachang commented on app/views/projects/_projectnav.html.erb
> +                              <svg class="fill-current" height="16" focusable="false" viewBox="0 0 32 32"><path
這裡怎麼了

2022-09-05 10:42 UTC, cacachang commented on app/views/projects/_projectnav.html.erb
> +                                    </div>
這裡的排版怎麼了

2022-09-05 17:10 UTC, KathyLEEKUANYI commented on app/views/home/index.html.erb
> +      <div class="flex w-full items-center p-2 transition-all rounded-md text-sm font-semibold text-gray-600 hover:bg-light">
這裡不是我的

2022-09-05 17:11 UTC, KathyLEEKUANYI commented on app/views/layouts/shared/_search_form.html.erb
> +  <%= f.label ""%>
空標籤就不會顯示form表單的字(原本是放search)
這裡因為有套搜尋的圖(放大鏡) 位置剛好重複所以拿掉

2022-09-05 17:23 UTC, KathyLEEKUANYI commented on app/views/projects/_projectnav.html.erb
> +                              <svg class="fill-current" height="16" focusable="false" viewBox="0 0 32 32"><path
PROJECT不是我的

2022-09-05 17:23 UTC, KathyLEEKUANYI commented on app/views/projects/_projectnav.html.erb
> +                                    </div>
PROJECT不是我的

2022-09-05 17:23 UTC, KathyLEEKUANYI commented on app/views/projects/_projectnav.html.erb
> +                          <span class="w-9 h-9 flex items-center justify-center text-icon">
PROJECT不是我的

2022-09-05 17:24 UTC, KathyLEEKUANYI commented on app/views/projects/_projectnav.html.erb
> +                        <span class="w-9 h-9 flex items-center justify-center text-icon">
PROJECT不是我的

2022-09-06 04:54 UTC, AilaLu approved these changes

2022-09-06 06:47 UTC, DylanHHY approved these changes

2022-09-06 10:04 UTC, closed without merging