group add tailwind/已解衝突
AC11-Take-Off-Team/Lax pull request #31
Opened 2022-09-05 08:35 UTC by KathyLEEKUANYI

2022-09-05 10:53 UTC, cacachang requested changes

2022-09-05 10:53 UTC, cacachang commented on app/views/groups/content.html.erb
> +      <div class="my-2 text-2xl ml-6">
縮排沒改

2022-09-05 10:53 UTC, cacachang commented on app/views/groups/edit.html.erb
> +      <div>
這裡不用縮吧？

2022-09-05 10:53 UTC, cacachang commented on app/views/groups/new.html.erb
> +    <p class="my-6 text-gray-500">频道是你的團隊進行通信的地方。圍繞主题進行組織時其效果最佳，例如#市場營銷#。</p>
是說簡字何時要改掉～

2022-09-05 10:53 UTC, cacachang commented on app/views/groups/show.html.erb
> +    <div class="flex flex-row h-full w-full overflow-x-hidden">
縮排

2022-09-05 12:57 UTC, KathyLEEKUANYI commented on app/views/groups/content.html.erb
> +      <div class="my-2 text-2xl ml-6">
<div class="align-center justify-between flex">
      <span class="my-6 text-2xl text-gray-900 font-semibold ml-6"><%= @group.title %></span>
      <span class="my-6 text-gray-400 text-2xl mr-6 bg-white hover:bg-gray-100 py-1 px-2 rounded-lg "><%= link_to "X", @group %></span>
    </div>

這樣是一組

      <div class="my-2 text-2xl ml-6">
        <div class="text-gray-700 font-bold py-2">描述:</div>
        <div class="p-1 mt-5"><%= @group.description %></div>
      </div>

這是另一組

2022-09-05 13:00 UTC, KathyLEEKUANYI commented on app/views/groups/edit.html.erb
> +      <div>
<div class="text-gray-700 font-bold py-2">名稱:</div>

---------------------------
      <div>
        <%= form.text_field :title ,:class=>"text-gray-700 shadow border rounded border-gray-300 focus:outline-none focus:shadow-outline py-1 px-3 mb-3", placeholder:"名稱"  %>
      </div>

2022-09-05 13:01 UTC, KathyLEEKUANYI commented on app/views/groups/new.html.erb
> +    <p class="my-6 text-gray-500">频道是你的團隊進行通信的地方。圍繞主题進行組織時其效果最佳，例如#市場營銷#。</p>
哪個是簡字？看起來沒有？）

2022-09-06 04:57 UTC, AilaLu approved these changes

2022-09-06 06:18 UTC, closed without merging