[功能] 全站搜尋
AC11-Take-Off-Team/Lax pull request #6
Opened 2022-08-25 11:17 UTC by KathyLEEKUANYI

增加搜尋功能
新增頻道

2022-08-25 12:53 UTC, DylanHHY commented
請先發pr跟dev合併

2022-08-26 03:04 UTC, cacachang requested changes

2022-08-26 03:04 UTC, cacachang commented on app/controllers/application_controller.rb
> +    @q = Group.ransack(params[:q])
q 是什麼？

2022-08-26 03:04 UTC, cacachang commented on config/routes.rb
> +      post :quit
quit 改 leave 會不會比較好？

2022-08-26 03:04 UTC, cacachang commented on app/controllers/groups_controller.rb
> +  before_action :find_group,only:[:show , :edit , :update,:destroy , :join , :quit]
排版請調整

2022-08-26 03:04 UTC, cacachang commented on app/controllers/groups_controller.rb
> +    @group = current_user.groups.build(clean)
clean 是 clean 什麼呢？

2022-08-26 03:04 UTC, cacachang commented on app/controllers/groups_controller.rb
> +    if @group.destroy
這邊怪怪的 沒有做 @group.destroy 就判斷了？

2022-08-26 03:04 UTC, cacachang commented on app/controllers/groups_controller.rb
> +      redirect_to groups_path
要不要給個 notice ?

2022-08-26 03:04 UTC, cacachang commented on app/controllers/groups_controller.rb
> +  def update
要不要給個 notice ?

2022-08-26 03:04 UTC, cacachang commented on app/models/group.rb
> +  has_many :channels
第三方要不要改慣例命名 感覺很容易搞混

2022-08-26 03:04 UTC, cacachang commented on app/controllers/groups_controller.rb
> +      flash[:notice] = "已加入"
為什麼 else 要給 已加入的 notice ? 不是在 if 就該給嗎？

2022-08-26 03:04 UTC, cacachang commented on app/controllers/application_controller.rb
> +
空格可以刪除

2022-08-26 03:04 UTC, cacachang commented on app/controllers/groups_controller.rb
> +      flash[:notice] = "已退出"
已退出是不是該放在 if ？

2022-08-26 03:04 UTC, cacachang commented on app/views/groups/new.html.erb
> +    <h1>創建頻道</h1>
排版！

2022-08-26 03:04 UTC, cacachang commented on app/views/groups/new.html.erb
> +當频道设置為私人时，只有受邀请之後才能查看或加入。
簡字？

2022-08-26 03:04 UTC, cacachang commented on app/views/groups/new.html.erb
> +當频道设置為私人时，只有受邀请之後才能查看或加入。
排版！！

2022-08-26 03:04 UTC, cacachang commented on app/views/groups/index.html.erb
> +  <% @group.each do |group| %>
排版！

2022-08-26 03:04 UTC, cacachang commented on app/views/groups/index.html.erb
> +        <%= link_to "退出" , quit_group_path(@group),method: "post"  %>
為什麼退出是用 post ?

2022-08-26 03:04 UTC, cacachang commented on app/controllers/application_controller.rb
> +  before_action :search
這方法應該可以放 GroupsController ?

2022-08-26 03:11 UTC, DylanHHY requested changes

2022-08-26 03:11 UTC, DylanHHY commented on app/controllers/application_controller.rb
> +    @q = Group.ransack(params[:q])
q是代表什麼？

2022-08-26 03:11 UTC, DylanHHY commented on app/views/groups/new.html.erb
> +當频道设置為私人时，只有受邀请之後才能查看或加入。
簡字？

2022-08-26 03:11 UTC, DylanHHY commented on app/views/layouts/application.html.erb
> +    <%= link_to "頻道" , groups_path %>
你頻道的連結不應該放在application裡面吧？
還是你有特別的需求

2022-08-26 03:11 UTC, DylanHHY commented on app/views/groups/new.html.erb
> +    <h1>創建頻道</h1>
h1 ?

2022-08-26 04:13 UTC, puyichun reviewed
改

2022-08-26 04:13 UTC, puyichun commented on app/controllers/application_controller.rb
> +    @q = Group.ransack(params[:q])
params[:q]，q哪來的？使用者怎麼會知道我們的欄位名

2022-08-26 04:13 UTC, puyichun commented on app/controllers/groups_controller.rb
> +    if @group.destroy
為什麼要if？

2022-08-26 04:13 UTC, puyichun commented on app/controllers/application_controller.rb
> +    @q = Group.ransack(params[:q])
實體變數不要叫＠q，看不出來這名字他在做什麼

2022-08-26 04:13 UTC, puyichun commented on app/controllers/groups_controller.rb
> +    @group = Group.order("created_at DESC")
index應該用@groups吧

2022-08-26 04:13 UTC, puyichun commented on app/controllers/groups_controller.rb
> +    @group = @q.result(distinct: true)
為什麼有兩個@group

2022-08-26 04:13 UTC, puyichun commented on app/controllers/groups_controller.rb
> +    participated_groups.include?(group)
participated_groups哪來的?

2022-08-26 04:13 UTC, puyichun commented on app/views/groups/index.html.erb
> +  <% @group.each do |group| %>
@groups

2022-08-26 04:13 UTC, puyichun commented on app/views/layouts/application.html.erb
> +    <%= link_to "頻道" , groups_path %>
寫render

2022-08-26 06:10 UTC, closed without merging