Feature/group tailwind 改縮排＋按鈕顏色
AC11-Take-Off-Team/Lax pull request #90
Opened 2022-09-09 14:23 UTC by KathyLEEKUANYI

這裡沒有nav檔案 所以layouts的搜尋先拿掉 首頁那裡合併我在放上去

2022-09-09 14:23 UTC, KathyLEEKUANYI commented
<img width="1089" alt="截圖 2022-09-09 下午6 47 01" src="https://user-images.githubusercontent.com/110835644/189372525-5bbe9baf-ddbf-4ef4-a13a-5559767a7a4a.png">

2022-09-09 14:24 UTC, KathyLEEKUANYI commented
<img width="1318" alt="截圖 2022-09-09 下午10 21 06" src="https://user-images.githubusercontent.com/110835644/189372697-da59df5a-0775-42a8-8870-12107cb5788e.png">

2022-09-09 14:28 UTC, KathyLEEKUANYI commented
<img width="531" alt="截圖 2022-09-09 下午10 27 29" src="https://user-images.githubusercontent.com/110835644/189373441-67ad9da8-f37f-4330-98fb-4c3152a1eb7e.png">
已改

2022-09-09 14:29 UTC, KathyLEEKUANYI commented
<img width="713" alt="截圖 2022-09-09 下午10 26 42" src="https://user-images.githubusercontent.com/110835644/189373741-9f9725e6-c713-4665-9656-92c69dde3506.png">
縮排ＡＭＤ

2022-09-09 14:30 UTC, KathyLEEKUANYI commented
<img width="798" alt="截圖 2022-09-09 下午10 26 18" src="https://user-images.githubusercontent.com/110835644/189373860-82198220-abdc-4bdc-b805-9d57d5b5263f.png">
改成ＤＥＬＥＴＥ

2022-09-09 14:30 UTC, KathyLEEKUANYI commented
<img width="792" alt="截圖 2022-09-09 下午10 25 59" src="https://user-images.githubusercontent.com/110835644/189373928-73b2add3-67cc-4d7d-885a-d8c7ab559202.png">
ＩＤ拿掉

2022-09-09 14:31 UTC, KathyLEEKUANYI commented
<img width="670" alt="截圖 2022-09-09 下午10 25 28" src="https://user-images.githubusercontent.com/110835644/189374000-62e1f610-f879-418a-abf1-ccd08594ebe5.png">
ＳＥＡＲＣＨ移動到ＧＲＯＵＰ

2022-09-10 09:57 UTC, puyichun requested changes

2022-09-10 09:57 UTC, puyichun commented on app/controllers/groups_controller.rb
> +    @group = current_user.groups.create(group_params)
用new吧，create都已經存進去了，何必要save

2022-09-10 09:57 UTC, puyichun commented on app/controllers/groups_controller.rb
> +    # if @group.private == true
這些註解怎麼沒有刪？

2022-09-10 09:57 UTC, puyichun commented on app/controllers/groups_controller.rb
> +      current_user.groups << [@group]
[]可以去掉

2022-09-10 09:57 UTC, puyichun commented on app/models/user.rb
> +  # validates :nickname, presence: true, uniqueness: true
解衝突時沒看到重複嗎？

2022-09-10 10:14 UTC, KathyLEEKUANYI commented on app/models/user.rb
> +  # validates :nickname, presence: true, uniqueness: true
那個是註解  所以已經確定要刪掉不改了?

2022-09-10 10:15 UTC, KathyLEEKUANYI commented on app/controllers/groups_controller.rb
> +    # if @group.private == true
公開私人的設定  但我這webpack又壞掉了目前掛上去看不到效果 寫好先放著

2022-09-10 10:16 UTC, KathyLEEKUANYI commented on app/controllers/groups_controller.rb
> +    @group = current_user.groups.create(group_params)
上次ning 說要改成create  現在又要改save....?
我試過都是會存檔
可以統一一下嗎...?

2022-09-10 10:28 UTC, closed without merging